<?php

/*
***********************************************************************************************************
  *                 Premium WordPress Themes by http://wpthms.com                *
    *                                   Copyright (c) wpthms.com                                        *
  *                                 http://themeforest.net/user/wpthms                                *    
*                                                                                                         *
  *                            -------------------------------------------                              *
    *                                     DO NOT EDIT THIS FILE                                       *
  *                                                                                                     *
***********************************************************************************************************

 
 * To add custom PHP functions to the theme, create a new 'custom-functions.php' file in the theme folder.
 *
 **********************************************************************************************************/

define( 'wpthms_DIR', get_template_directory() . '/' );
define( 'wpthms_URI', get_template_directory_uri() . '/' );
define( 'THEME_VERSION', 2.0 );

if ( isset( $content_width ) )
	$content_width = 710;

/**
 * Include theme framework
 */
$theme_includes = apply_filters( 'yt_locate_template_wpthms_functions_includes',
	array(	
		'framework/admin/init.php',
		'framework/yt-admin-init.php',
		'includes/theme-init.php',
		'custom-functions.php',
	)
);
			
foreach ( $theme_includes as $include ) { 
	locate_template( $include, true ); 
}